config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)
  resources :dish_in_baskets, :baskets, :categories
  root 'list#main'
  get 'list_one/:id' => 'list#one', as: 'list_one'
  get 'list_category/:id' => 'list#category', as: 'list_category'
  # scope :admin do
  # 	resources :dishes, :caves 
  # end
  scope :list_one do
  	resources :dish_in_baskets, only: [:create, :destroy] 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basket.rb
class Basket < ApplicationRecord
	belongs_to :user
	has_many :dish_in_baskets
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :destroy]

  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all
  end

  # GET /baskets/1
  # GET /baskets/1.json
 

  # GET /baskets/new
  def new
    @basket = Basket.new
  end

  # GET /baskets/1/edit


  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(basket_params)

    respond_to do |format|
      if @basket.save
        format.html { redirect_to :back, notice: 'Basket was successfully created.' }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baskets/1
  # PATCH/PUT /baskets/1.json
  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket }
      else
        format.html { render :edit }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket.destroy
    respond_to do |format|
      format.html { redirect_to baskets_url, notice: 'Basket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket
      @basket = Basket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_params
      params.require(:basket).permit(:user_id, :cafe_id)
    end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/_form.html.erb
<%= form_for(basket) do |f| %>
  <% if basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing Basket</h1>

<%= render 'form', basket: @basket %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Baskets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <td><%= basket.user_id %></td>
        <td><%= link_to 'Show', basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New Basket</h1>

<%= render 'form', basket: @basket %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @basket.user_id %>
</p>

<%= link_to 'Edit', edit_basket_path(@basket) %> |
<%= link_to 'Back', baskets_path %>