config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)
  resources :dish_in_baskets, :baskets, :categories
  root 'list#main'
  get 'list_one/:id' => 'list#one', as: 'list_one'
  get 'list_category/:id' => 'list#category', as: 'list_category'
  # scope :admin do
  # 	resources :dishes, :caves 
  # end
  scope :list_one do
  	resources :dish_in_baskets, only: [:create, :destroy] 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dish_in_basket.rb
class DishInBasket < ApplicationRecord
	belongs_to :dish
	belongs_to :basket
end

app/controllers/dish_in_baskets_controller.rb
class DishInBasketsController < ApplicationController
  before_action :set_dish_in_basket, only: [:show, :edit, :update, :destroy]

  # GET /dish_in_baskets
  # GET /dish_in_baskets.json
  def index
    @dish_in_baskets = DishInBasket.all
  end

  # GET /dish_in_baskets/1
  # GET /dish_in_baskets/1.json


  # GET /dish_in_baskets/new
  def new
    @dish_in_basket = DishInBasket.new
  end

  # GET /dish_in_baskets/1/edit
 

  # POST /dish_in_baskets
  # POST /dish_in_baskets.json
  def create
    @dish_in_basket = DishInBasket.new(dish_in_basket_params)

    respond_to do |format|
      if @dish_in_basket.save
        format.html { redirect_to :back, notice: 'Dish in basket was successfully created.' }
        format.json { render :show, status: :created, location: @dish_in_basket }
        format.js {}
      else

        format.html { render :new }
        format.json { render json: @dish_in_basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dish_in_baskets/1
  # PATCH/PUT /dish_in_baskets/1.json
  def update
    respond_to do |format|
      if @dish_in_basket.update(dish_in_basket_params)
        format.html { redirect_to @dish_in_basket, notice: 'Dish in basket was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish_in_basket }
      else
        format.html { render :edit }
        format.json { render json: @dish_in_basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dish_in_baskets/1
  # DELETE /dish_in_baskets/1.json
  def destroy
    DishInBasket.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Dish in basket was successfully destroyed.' }
      format.json { head :no_content }
      format.js {} 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish_in_basket
      @dish_in_basket = DishInBasket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_in_basket_params
      params.require(:dish_in_basket).permit(:basket_id, :dish_id, :title, :price, :quantity, :total)
    end
end

app/helpers/dish_in_baskets_helper.rb
module DishInBasketsHelper
end

app/views/dish_in_baskets/_dish_in_basket.html.erb
 Ваш заказ:</br>
    <% total_sum = 0 %>
    <% current_user.baskets.last.dish_in_baskets.each do |dish_in_basket| %>
       <div data-id="<%= dish_in_basket.id %>">
	        <%= dish_in_basket.quantity %>
	        <%= dish_in_basket.dish.title %>
	        <%= dish_in_basket.dish.price %>
	        <%= link_to 'Delete', dish_in_basket_path(dish_in_basket), method: 'delete', remote: true %>
	        <%= total = dish_in_basket.dish.price * dish_in_basket.quantity %> 
	        <% total_sum += total %>
	        <br>
        </div>     
    <% end %> 
    Итого:<%= total_sum %>

app/views/dish_in_baskets/_form.html.erb
<%= form_for [@dish.dish_in_basket.build], remote: true do |f| %>
  <% if dish_in_basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish_in_basket.errors.count, "error") %> prohibited this dish_in_basket from being saved:</h2>

      <ul>
      <% dish_in_basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :basket_id %>
    <%= f.number_field :basket_id %>
  </div>

  <div class="field">
    <%= f.label :dish_id %>
    <%= f.number_field :dish_id %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.number_field :total %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dish_in_baskets/create.js.erb
$("#dish_in_basket").html("<%= j render 'dish_in_baskets/dish_in_basket'%>");
$("#dish_in_basket_dish_title").val("");
$("#dish_in_basket_dish_price").val("");
$("#dish_in_basket_dish_quantity").val("");
$("#dish_in_basket_total").val("");

app/views/dish_in_baskets/destroy.js.erb
$('[data-id="<%= params[:id] %>"]').remove();

app/views/dish_in_baskets/edit.html.erb
<h1>Editing Dish In Basket</h1>

<%= render 'form', dish_in_basket: @dish_in_basket %>

<%= link_to 'Show', @dish_in_basket %> |
<%= link_to 'Back', dish_in_baskets_path %>

app/views/dish_in_baskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dish In Baskets</h1>

<table>
  <thead>
    <tr>
      <th>Basket</th>
      <th>Dish</th>
      <th>Title</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dish_in_baskets.each do |dish_in_basket| %>
      <tr>
        <td><%= dish_in_basket.basket_id %></td>
        <td><%= dish_in_basket.dish_id %></td>
        <td><%= dish_in_basket.title %></td>
        <td><%= dish_in_basket.price %></td>
        <td><%= dish_in_basket.quantity %></td>
        <td><%= dish_in_basket.total %></td>
        <td><%= link_to 'Show', dish_in_basket %></td>
        <td><%= link_to 'Edit', edit_dish_in_basket_path(dish_in_basket) %></td>
        <td><%= link_to 'Destroy', dish_in_basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish In Basket', new_dish_in_basket_path %>

app/views/dish_in_baskets/new.html.erb
<h1>New Dish In Basket</h1>

<%= render 'form', dish_in_basket: @dish_in_basket %>

<%= link_to 'Back', dish_in_baskets_path %>

app/views/dish_in_baskets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Basket:</strong>
  <%= @dish_in_basket.basket_id %>
</p>

<p>
  <strong>Dish:</strong>
  <%= @dish_in_basket.dish.title %>
</p>

<p>
  <strong>Title:</strong>
  <%= @dish_in_basket.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish_in_basket.dish.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @dish_in_basket.quantity %>
</p>

<p>
  <strong>Total:</strong>
  <%= @dish_in_basket.total %>
</p>

<%= link_to 'Edit', edit_dish_in_basket_path(@dish_in_basket) %> |
<%= link_to 'Back', dish_in_baskets_path %>